# Generated by Django 4.1 on 2024-05-08 11:31

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0005_lecture'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='is_available_to',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
